In [1]:
import sys
import pandas as pd
import numpy as np

# Task 1

In [55]:
df = pd.read_csv('/Users/matveyspiridonov/Downloads/_ea07570741a3ec966e284208f588e50e_titanic.csv')

In [56]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [4]:
df['Sex'].value_counts()

male      577
female    314
Name: Sex, dtype: int64

In [8]:
df[df['Survived'] == 1].shape[0] / df.shape[0]

0.3838383838383838

In [9]:
df[df['Pclass'] == 1].shape[0] / df.shape[0]

0.24242424242424243

In [15]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [17]:
df.corr()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
PassengerId,1.000000,-0.005007,-0.035144,0.036847,-0.057527,-0.001652,0.012658
Survived,-0.005007,1.000000,-0.338481,-0.077221,-0.035322,0.081629,0.257307
Pclass,-0.035144,-0.338481,1.000000,-0.369226,0.083081,0.018443,-0.549500
Age,0.036847,-0.077221,-0.369226,1.000000,-0.308247,-0.189119,0.096067
SibSp,-0.057527,-0.035322,0.083081,-0.308247,1.000000,0.414838,0.159651
Parch,-0.001652,0.081629,0.018443,-0.189119,0.414838,1.000000,0.216225
Fare,0.012658,0.257307,-0.549500,0.096067,0.159651,0.216225,1.000000

In [32]:
df[df['Sex'] == 'female']['Name'].apply(lambda x: x.split()[2]).value_counts()

William      13
Anna          9
Mary          9
Thomas        6
Elizabeth     6
             ..
Elina         1
Mara          1
Gladys        1
Karl          1
Richard       1
Name: Name, Length: 202, dtype: int64

# Task 2

In [60]:
df1 = df[['Pclass','Age','Fare','Sex','Survived']]
df1 = df1.dropna()
df1

     Pclass   Age     Fare     Sex  Survived
0         3  22.0   7.2500    male         0
1         1  38.0  71.2833  female         1
2         3  26.0   7.9250  female         1
3         1  35.0  53.1000  female         1
4         3  35.0   8.0500    male         0
..      ...   ...      ...     ...       ...
885       3  39.0  29.1250  female         0
886       2  27.0  13.0000    male         0
887       1  19.0  30.0000  female         1
889       1  26.0  30.0000    male         1
890       3  32.0   7.7500    male         0

[714 rows x 5 columns]

In [61]:
y = df1['Survived']
X = df1.drop('Survived', axis = 1)

In [64]:
X['Sex'] = X['Sex'].apply(lambda x: 1 if x == 'male' else 0)

In [65]:
X

     Pclass   Age     Fare  Sex
0         3  22.0   7.2500    1
1         1  38.0  71.2833    0
2         3  26.0   7.9250    0
3         1  35.0  53.1000    0
4         3  35.0   8.0500    1
..      ...   ...      ...  ...
885       3  39.0  29.1250    0
886       2  27.0  13.0000    1
887       1  19.0  30.0000    0
889       1  26.0  30.0000    1
890       3  32.0   7.7500    1

[714 rows x 4 columns]

In [66]:
from sklearn.tree import DecisionTreeClassifier

In [67]:
model = DecisionTreeClassifier(random_state=241)
model.fit(X,y)

DecisionTreeClassifier(random_state=241)

In [68]:
model.feature_importances_

array([0.13700004, 0.2560461 , 0.30644165, 0.30051221])

# Task 3

In [4]:
df2 = pd.read_csv("/Users/matveyspiridonov/Downloads/wine.data", header=None)
df2.columns=[i for i in range(14)]
df2

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,3,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740
174,3,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750
175,3,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835
176,3,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840
177,3,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560

In [41]:
from sklearn.neighbors import KNeighborsClassifier as KNN
from sklearn.neighbors import KNeighborsRegressor as KNNR
from sklearn.model_selection import KFold
from sklearn.metrics import accuracy_score as accuracy
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import scale
import sklearn.datasets

In [8]:
split = KFold(n_splits = 5, shuffle = True, random_state = 42)

In [21]:
for i in range(1, 50):
    crs = cross_val_score(KNN(n_neighbors = i), df2.drop(0, axis = 1), df2[0], cv = split,scoring = 'accuracy')
    print(crs, crs.mean())

[0.77777778 0.66666667 0.72222222 0.71428571 0.77142857] 0.7304761904761905
[0.72222222 0.63888889 0.69444444 0.57142857 0.68571429] 0.6625396825396825
[0.80555556 0.61111111 0.63888889 0.65714286 0.82857143] 0.7082539682539682
[0.75       0.52777778 0.61111111 0.65714286 0.74285714] 0.6577777777777778
[0.72222222 0.61111111 0.61111111 0.68571429 0.74285714] 0.6746031746031746
[0.72222222 0.63888889 0.63888889 0.68571429 0.68571429] 0.6742857142857144
[0.69444444 0.58333333 0.72222222 0.68571429 0.71428571] 0.68
[0.72222222 0.61111111 0.66666667 0.65714286 0.74285714] 0.6799999999999999
[0.72222222 0.63888889 0.72222222 0.68571429 0.74285714] 0.7023809523809523
[0.72222222 0.61111111 0.63888889 0.68571429 0.74285714] 0.6801587301587302
[0.75       0.63888889 0.66666667 0.71428571 0.74285714] 0.7025396825396826
[0.72222222 0.66666667 0.69444444 0.68571429 0.71428571] 0.6966666666666667
[0.72222222 0.69444444 0.66666667 0.65714286 0.71428571] 0.6909523809523809
[0.72222222 0.66666667 0.72222222 0.6        0.68571429] 0.6793650793650794
[0.75       0.72222222 0.69444444 0.62857143 0.71428571] 0.701904761904762
[0.72222222 0.63888889 0.72222222 0.6        0.71428571] 0.6795238095238096
[0.77777778 0.72222222 0.72222222 0.6        0.68571429] 0.7015873015873015
[0.77777778 0.61111111 0.69444444 0.6        0.71428571] 0.6795238095238095
[0.77777778 0.63888889 0.69444444 0.6        0.68571429] 0.6793650793650793
[0.77777778 0.61111111 0.69444444 0.62857143 0.74285714] 0.6909523809523809
[0.77777778 0.63888889 0.75       0.62857143 0.71428571] 0.7019047619047619
[0.77777778 0.63888889 0.69444444 0.62857143 0.74285714] 0.6965079365079364
[0.77777778 0.63888889 0.72222222 0.6        0.77142857] 0.7020634920634921
[0.77777778 0.63888889 0.75       0.62857143 0.74285714] 0.7076190476190476
[0.77777778 0.63888889 0.75       0.62857143 0.71428571] 0.7019047619047619
[0.77777778 0.61111111 0.72222222 0.65714286 0.71428571] 0.6965079365079365
[0.77777778 0.63888889 0.72222222 0.62857143 0.71428571] 0.6963492063492064
[0.77777778 0.61111111 0.72222222 0.68571429 0.74285714] 0.7079365079365079
[0.77777778 0.63888889 0.72222222 0.68571429 0.74285714] 0.7134920634920634
[0.77777778 0.61111111 0.72222222 0.68571429 0.74285714] 0.7079365079365079
[0.77777778 0.58333333 0.72222222 0.62857143 0.74285714] 0.690952380952381
[0.80555556 0.61111111 0.72222222 0.68571429 0.74285714] 0.7134920634920634
[0.77777778 0.61111111 0.75       0.68571429 0.74285714] 0.7134920634920634
[0.83333333 0.61111111 0.75       0.68571429 0.74285714] 0.7246031746031747
[0.80555556 0.66666667 0.72222222 0.68571429 0.74285714] 0.7246031746031747
[0.83333333 0.61111111 0.69444444 0.68571429 0.74285714] 0.7134920634920636
[0.80555556 0.61111111 0.72222222 0.68571429 0.74285714] 0.7134920634920634
[0.80555556 0.61111111 0.72222222 0.68571429 0.74285714] 0.7134920634920634
[0.77777778 0.61111111 0.72222222 0.68571429 0.74285714] 0.7079365079365079
[0.80555556 0.61111111 0.72222222 0.68571429 0.71428571] 0.7077777777777777
[0.80555556 0.61111111 0.72222222 0.68571429 0.74285714] 0.7134920634920634
[0.80555556 0.61111111 0.72222222 0.68571429 0.71428571] 0.7077777777777777
[0.80555556 0.61111111 0.72222222 0.68571429 0.71428571] 0.7077777777777777
[0.80555556 0.61111111 0.72222222 0.68571429 0.71428571] 0.7077777777777777
[0.80555556 0.61111111 0.72222222 0.68571429 0.71428571] 0.7077777777777777
[0.80555556 0.61111111 0.72222222 0.68571429 0.71428571] 0.7077777777777777
[0.75       0.61111111 0.72222222 0.68571429 0.71428571] 0.6966666666666667
[0.83333333 0.61111111 0.72222222 0.71428571 0.71428571] 0.7190476190476192
[0.75       0.61111111 0.72222222 0.68571429 0.71428571] 0.6966666666666667

In [30]:
X = scale(df2.drop(0, axis = 1))

In [32]:
for i in range(1, 50):
    crs = cross_val_score(KNN(n_neighbors = i), X, df2[0], cv = split,scoring = 'accuracy')
    print(crs, crs.mean(), i)

[0.94444444 0.94444444 0.91666667 0.97142857 0.94285714] 0.943968253968254 1
[0.94444444 0.88888889 0.91666667 0.97142857 0.94285714] 0.9328571428571429 2
[0.94444444 0.94444444 0.97222222 0.97142857 0.94285714] 0.9550793650793651 3
[0.94444444 0.91666667 0.94444444 0.94285714 0.94285714] 0.9382539682539683 4
[0.94444444 0.94444444 0.97222222 0.91428571 0.97142857] 0.9493650793650794 5
[0.94444444 0.91666667 0.97222222 0.97142857 0.94285714] 0.9495238095238095 6
[0.94444444 0.91666667 0.97222222 0.94285714 0.97142857] 0.9495238095238095 7
[0.94444444 0.91666667 0.97222222 0.97142857 0.97142857] 0.9552380952380952 8
[0.94444444 0.94444444 0.97222222 0.94285714 1.        ] 0.9607936507936508 9
[0.94444444 0.94444444 0.97222222 0.97142857 0.97142857] 0.9607936507936508 10
[0.94444444 0.94444444 0.94444444 0.97142857 1.        ] 0.9609523809523809 11
[0.97222222 0.91666667 0.94444444 0.97142857 0.97142857] 0.9552380952380952 12
[0.94444444 0.94444444 0.94444444 0.91428571 1.        ] 0.9495238095238093 13
[0.97222222 0.94444444 0.97222222 0.97142857 0.97142857] 0.9663492063492063 14
[0.97222222 0.94444444 0.97222222 0.97142857 1.        ] 0.9720634920634922 15
[0.97222222 0.94444444 0.97222222 0.97142857 1.        ] 0.9720634920634922 16
[0.97222222 0.91666667 0.97222222 0.97142857 1.        ] 0.9665079365079364 17
[0.97222222 0.91666667 0.97222222 0.97142857 1.        ] 0.9665079365079364 18
[0.94444444 0.91666667 0.94444444 0.97142857 1.        ] 0.9553968253968254 19
[0.97222222 0.91666667 0.97222222 0.97142857 1.        ] 0.9665079365079364 20
[0.94444444 0.91666667 0.97222222 0.97142857 1.        ] 0.9609523809523811 21
[0.94444444 0.94444444 0.97222222 0.97142857 1.        ] 0.9665079365079364 22
[0.94444444 0.94444444 0.94444444 0.97142857 1.        ] 0.9609523809523809 23
[0.94444444 0.94444444 0.94444444 0.97142857 0.97142857] 0.9552380952380952 24
[0.94444444 0.94444444 0.94444444 0.97142857 0.97142857] 0.9552380952380952 25
[0.94444444 0.94444444 0.97222222 0.97142857 0.97142857] 0.9607936507936508 26
[0.94444444 0.94444444 0.94444444 0.97142857 0.97142857] 0.9552380952380952 27
[0.97222222 0.94444444 0.97222222 0.97142857 0.97142857] 0.9663492063492063 28
[1.         0.94444444 0.97222222 0.97142857 1.        ] 0.9776190476190475 29
[0.97222222 0.91666667 0.97222222 0.97142857 0.97142857] 0.9607936507936508 30
[0.97222222 0.91666667 0.94444444 0.97142857 0.97142857] 0.9552380952380952 31
[0.97222222 0.91666667 0.97222222 0.97142857 0.97142857] 0.9607936507936508 32
[1.         0.91666667 0.97222222 0.97142857 0.97142857] 0.9663492063492063 33
[1.         0.91666667 0.97222222 0.97142857 0.97142857] 0.9663492063492063 34
[1.         0.88888889 0.97222222 0.97142857 0.97142857] 0.9607936507936508 35
[0.97222222 0.91666667 0.97222222 0.97142857 0.97142857] 0.9607936507936508 36
[0.97222222 0.88888889 0.97222222 0.97142857 0.97142857] 0.9552380952380952 37
[0.97222222 0.91666667 0.97222222 0.97142857 0.97142857] 0.9607936507936508 38
[0.97222222 0.91666667 0.97222222 0.97142857 0.97142857] 0.9607936507936508 39
[0.97222222 0.91666667 0.97222222 0.97142857 0.97142857] 0.9607936507936508 40
[1.         0.91666667 0.97222222 0.97142857 0.97142857] 0.9663492063492063 41
[0.94444444 0.94444444 0.97222222 0.97142857 0.97142857] 0.9607936507936508 42
[1.         0.91666667 0.97222222 0.97142857 0.97142857] 0.9663492063492063 43
[1.         0.91666667 0.97222222 0.97142857 0.94285714] 0.9606349206349206 44
[1.         0.91666667 0.97222222 0.97142857 0.97142857] 0.9663492063492063 45
[0.94444444 0.91666667 0.97222222 0.97142857 0.94285714] 0.9495238095238095 46
[0.97222222 0.91666667 0.97222222 0.97142857 0.94285714] 0.9550793650793651 47
[0.94444444 0.91666667 0.97222222 0.97142857 0.94285714] 0.9495238095238095 48
[0.97222222 0.91666667 0.97222222 0.97142857 0.94285714] 0.9550793650793651 49

In [37]:
df3 = sklearn.datasets.load_boston()
df3

{'data': array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
         4.9800e+00],
        [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
         9.1400e+00],
        [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
         4.0300e+00],
        ...,
        [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         5.6400e+00],
        [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
         6.4800e+00],
        [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         7.8800e+00]]),
 'target': array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
        18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
        15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
        13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
        21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
        35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
        19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
        20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
        23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
        33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
        21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
        20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
        23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
        15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21.5, 19.6, 15.3, 19.4,
        17. , 15.6, 13.1, 41.3, 24.3, 23.3, 27. , 50. , 50. , 50. , 22.7,
        25. , 50. , 23.8, 23.8, 22.3, 17.4, 19.1, 23.1, 23.6, 22.6, 29.4,
        23.2, 24.6, 29.9, 37.2, 39.8, 36.2, 37.9, 32.5, 26.4, 29.6, 50. ,
        32. , 29.8, 34.9, 37. , 30.5, 36.4, 31.1, 29.1, 50. , 33.3, 30.3,
        34.6, 34.9, 32.9, 24.1, 42.3, 48.5, 50. , 22.6, 24.4, 22.5, 24.4,
        20. , 21.7, 19.3, 22.4, 28.1, 23.7, 25. , 23.3, 28.7, 21.5, 23. ,
        26.7, 21.7, 27.5, 30.1, 44.8, 50. , 37.6, 31.6, 46.7, 31.5, 24.3,
        31.7, 41.7, 48.3, 29. , 24. , 25.1, 31.5, 23.7, 23.3, 22. , 20.1,
        22.2, 23.7, 17.6, 18.5, 24.3, 20.5, 24.5, 26.2, 24.4, 24.8, 29.6,
        42.8, 21.9, 20.9, 44. , 50. , 36. , 30.1, 33.8, 43.1, 48.8, 31. ,
        36.5, 22.8, 30.7, 50. , 43.5, 20.7, 21.1, 25.2, 24.4, 35.2, 32.4,
        32. , 33.2, 33.1, 29.1, 35.1, 45.4, 35.4, 46. , 50. , 32.2, 22. ,
        20.1, 23.2, 22.3, 24.8, 28.5, 37.3, 27.9, 23.9, 21.7, 28.6, 27.1,
        20.3, 22.5, 29. , 24.8, 22. , 26.4, 33.1, 36.1, 28.4, 33.4, 28.2,
        22.8, 20.3, 16.1, 22.1, 19.4, 21.6, 23.8, 16.2, 17.8, 19.8, 23.1,
        21. , 23.8, 23.1, 20.4, 18.5, 25. , 24.6, 23. , 22.2, 19.3, 22.6,
        19.8, 17.1, 19.4, 22.2, 20.7, 21.1, 19.5, 18.5, 20.6, 19. , 18.7,
        32.7, 16.5, 23.9, 31.2, 17.5, 17.2, 23.1, 24.5, 26.6, 22.9, 24.1,
        18.6, 30.1, 18.2, 20.6, 17.8, 21.7, 22.7, 22.6, 25. , 19.9, 20.8,
        16.8, 21.9, 27.5, 21.9, 23.1, 50. , 50. , 50. , 50. , 50. , 13.8,
        13.8, 15. , 13.9, 13.3, 13.1, 10.2, 10.4, 10.9, 11.3, 12.3,  8.8,
         7.2, 10.5,  7.4, 10.2, 11.5, 15.1, 23.2,  9.7, 13.8, 12.7, 13.1,
        12.5,  8.5,  5. ,  6.3,  5.6,  7.2, 12.1,  8.3,  8.5,  5. , 11.9,
        27.9, 17.2, 27.5, 15. , 17.2, 17.9, 16.3,  7. ,  7.2,  7.5, 10.4,
         8.8,  8.4, 16.7, 14.2, 20.8, 13.4, 11.7,  8.3, 10.2, 10.9, 11. ,
         9.5, 14.5, 14.1, 16.1, 14.3, 11.7, 13.4,  9.6,  8.7,  8.4, 12.8,
        10.5, 17.1, 18.4, 15.4, 10.8, 11.8, 14.9, 12.6, 14.1, 13. , 13.4,
        15.2, 16.1, 17.8, 14.9, 14.1, 12.7, 13.5, 14.9, 20. , 16.4, 17.7,
        19.5, 20.2, 21.4, 19.9, 19. , 19.1, 19.1, 20.1, 19.9, 19.6, 23.2,
        29.8, 13.8, 13.3, 16.7, 12. , 14.6, 21.4, 23. , 23.7, 25. , 21.8,
        20.6, 21.2, 19.1, 20.6, 15.2,  7. ,  8.1, 13.6, 20.1, 21.8, 24.5,
        23.1, 19.7, 18.3, 21.2, 17.5, 16.8, 22.4, 20.6, 23.9, 22. , 11.9]),
 'feature_names': array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
        'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7'),
 'DESCR': ".. _boston_dataset:\n\nBoston house prices dataset\n---------------------------\n\n**Data Set Characteristics:**  \n\n    :Number of Instances: 506 \n\n    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.\n\n    :Attribute Information (in order):\n        - CRIM     per capita crime rate by town\n        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.\n        - INDUS    proportion of non-retail business acres per town\n        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)\n        - NOX      nitric oxides concentration (parts per 10 million)\n        - RM       average number of rooms per dwelling\n        - AGE      proportion of owner-occupied units built prior to 1940\n        - DIS      weighted distances to five Boston employment centres\n        - RAD      index of accessibility to radial highways\n        - TAX      full-value property-tax rate per $10,000\n        - PTRATIO  pupil-teacher ratio by town\n        - B        1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town\n        - LSTAT    % lower status of the population\n        - MEDV     Median value of owner-occupied homes in $1000's\n\n    :Missing Attribute Values: None\n\n    :Creator: Harrison, D. and Rubinfeld, D.L.\n\nThis is a copy of UCI ML housing dataset.\nhttps://archive.ics.uci.edu/ml/machine-learning-databases/housing/\n\n\nThis dataset was taken from the StatLib library which is maintained at Carnegie Mellon University.\n\nThe Boston house-price data of Harrison, D. and Rubinfeld, D.L. 'Hedonic\nprices and the demand for clean air', J. Environ. Economics & Management,\nvol.5, 81-102, 1978.   Used in Belsley, Kuh & Welsch, 'Regression diagnostics\n...', Wiley, 1980.   N.B. Various transformations are used in the table on\npages 244-261 of the latter.\n\nThe Boston house-price data has been used in many machine learning papers that address regression\nproblems.   \n     \n.. topic:: References\n\n   - Belsley, Kuh & Welsch, 'Regression diagnostics: Identifying Influential Data and Sources of Collinearity', Wiley, 1980. 244-261.\n   - Quinlan,R. (1993). Combining Instance-Based and Model-Based Learning. In Proceedings on the Tenth International Conference of Machine Learning, 236-243, University of Massachusetts, Amherst. Morgan Kaufmann.\n",
 'filename': '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/datasets/data/boston_house_prices.csv'}

In [38]:
X_ = df3['data']
X_

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [39]:
y_ = df3['target']
y_

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21.5, 19.6, 15.3, 19.4,
       17. , 15.6, 13.1, 41.3, 24.3, 23.3, 27. , 50. , 50. , 50. , 22.7,
       25. , 50. , 23.8, 23.8, 22.3, 17.4, 19.1, 23.1, 23.6, 22.6, 29.4,
       23.2, 24.6, 29.9, 37.2, 39.8, 36.2, 37.9, 32.5, 26.4, 29.6, 50. ,
       32. , 29.8, 34.9, 37. , 30.5, 36.4, 31.1, 29.1, 50. , 33.3, 30.3,
       34.6, 34.9, 32.9, 24.1, 42.3, 48.5, 50. , 22.6, 24.4, 22.5, 24.4,
       20. , 21.7, 19.3, 22.4, 28.1, 23.7, 25. , 23.3, 28.7, 21.5, 23. ,
       26.7, 21.7, 27.5, 30.1, 44.8, 50. , 37.6, 31.6, 46.7, 31.5, 24.3,
       31.7, 41.7, 48.3, 29. , 24. , 25.1, 31.5, 23.7, 23.3, 22. , 20.1,
       22.2, 23.7, 17.6, 18.5, 24.3, 20.5, 24.5, 26.2, 24.4, 24.8, 29.6,
       42.8, 21.9, 20.9, 44. , 50. , 36. , 30.1, 33.8, 43.1, 48.8, 31. ,
       36.5, 22.8, 30.7, 50. , 43.5, 20.7, 21.1, 25.2, 24.4, 35.2, 32.4,
       32. , 33.2, 33.1, 29.1, 35.1, 45.4, 35.4, 46. , 50. , 32.2, 22. ,
       20.1, 23.2, 22.3, 24.8, 28.5, 37.3, 27.9, 23.9, 21.7, 28.6, 27.1,
       20.3, 22.5, 29. , 24.8, 22. , 26.4, 33.1, 36.1, 28.4, 33.4, 28.2,
       22.8, 20.3, 16.1, 22.1, 19.4, 21.6, 23.8, 16.2, 17.8, 19.8, 23.1,
       21. , 23.8, 23.1, 20.4, 18.5, 25. , 24.6, 23. , 22.2, 19.3, 22.6,
       19.8, 17.1, 19.4, 22.2, 20.7, 21.1, 19.5, 18.5, 20.6, 19. , 18.7,
       32.7, 16.5, 23.9, 31.2, 17.5, 17.2, 23.1, 24.5, 26.6, 22.9, 24.1,
       18.6, 30.1, 18.2, 20.6, 17.8, 21.7, 22.7, 22.6, 25. , 19.9, 20.8,
       16.8, 21.9, 27.5, 21.9, 23.1, 50. , 50. , 50. , 50. , 50. , 13.8,
       13.8, 15. , 13.9, 13.3, 13.1, 10.2, 10.4, 10.9, 11.3, 12.3,  8.8,
        7.2, 10.5,  7.4, 10.2, 11.5, 15.1, 23.2,  9.7, 13.8, 12.7, 13.1,
       12.5,  8.5,  5. ,  6.3,  5.6,  7.2, 12.1,  8.3,  8.5,  5. , 11.9,
       27.9, 17.2, 27.5, 15. , 17.2, 17.9, 16.3,  7. ,  7.2,  7.5, 10.4,
        8.8,  8.4, 16.7, 14.2, 20.8, 13.4, 11.7,  8.3, 10.2, 10.9, 11. ,
        9.5, 14.5, 14.1, 16.1, 14.3, 11.7, 13.4,  9.6,  8.7,  8.4, 12.8,
       10.5, 17.1, 18.4, 15.4, 10.8, 11.8, 14.9, 12.6, 14.1, 13. , 13.4,
       15.2, 16.1, 17.8, 14.9, 14.1, 12.7, 13.5, 14.9, 20. , 16.4, 17.7,
       19.5, 20.2, 21.4, 19.9, 19. , 19.1, 19.1, 20.1, 19.9, 19.6, 23.2,
       29.8, 13.8, 13.3, 16.7, 12. , 14.6, 21.4, 23. , 23.7, 25. , 21.8,
       20.6, 21.2, 19.1, 20.6, 15.2,  7. ,  8.1, 13.6, 20.1, 21.8, 24.5,
       23.1, 19.7, 18.3, 21.2, 17.5, 16.8, 22.4, 20.6, 23.9, 22. , 11.9])

In [40]:
X_ = scale(X_)

In [46]:
a = []
for i in np.linspace(1,10,200):
    crs = cross_val_score(KNNR(n_neighbors=5, weights='distance', metric = 'minkowski', p = i), X_, y_, cv = split, scoring='neg_mean_squared_error')
    a.append([crs.mean(), i])
    print(crs, crs.mean(), i)

[-20.21899107 -12.49567191 -17.22129105 -11.83373336 -18.38354627] -16.030646734221644 1.0
[-20.22607648 -12.57429075 -17.43647464 -12.07494178 -19.72740989] -16.40783870832999 1.0452261306532664
[-20.13329413 -12.65479751 -17.68764499 -11.92277511 -19.45497299] -16.370696947059045 1.0904522613065326
[-20.20518452 -12.96135285 -17.65835017 -11.91533174 -19.48836227] -16.445716308439433 1.135678391959799
[-19.93196196 -12.90136373 -18.02078301 -11.95450061 -19.56667956] -16.475057773399403 1.1809045226130652
[-19.80364184 -12.87447015 -17.93740291 -12.11406897 -19.90257779] -16.526432329318258 1.2261306532663316
[-19.92462793 -13.24345009 -17.97716386 -12.09748856 -19.94081629] -16.636709345898257 1.271356783919598
[-19.85066747 -13.80890388 -17.68416088 -12.66957076 -20.10781828] -16.82422425426731 1.3165829145728645
[-19.87699063 -13.94042247 -17.88657538 -12.68019921 -19.98685759] -16.874209056598744 1.3618090452261307
[-19.86064833 -13.98675631 -19.19762903 -12.65965632 -19.9198041 ] -17.124898819792115 1.4070351758793969
[-19.882023   -13.69648154 -19.07122148 -12.97629251 -20.10014088] -17.145231882153887 1.4522613065326633
[-20.02953344 -13.77715181 -19.0196722  -13.01075677 -19.25968618] -17.01936008026763 1.4974874371859297
[-19.89372903 -13.85238523 -19.1250555  -13.39135032 -19.23313861] -17.09913173771377 1.542713567839196
[-19.61628777 -13.94959443 -19.30113917 -13.46192433 -17.6776875 ] -16.801326640288362 1.5879396984924623
[-19.6110258  -13.91642283 -19.69913171 -13.99604874 -17.6810969 ] -16.980745198189776 1.6331658291457287
[-19.62704139 -13.94838768 -19.25220341 -14.64195111 -17.69771093] -17.03345890364771 1.678391959798995
[-19.63039693 -14.07107144 -19.80555743 -14.63803981 -17.7131439 ] -17.17164190266228 1.7236180904522613
[-19.77161942 -13.86881731 -19.6791269  -14.80860428 -17.78022795] -17.181679169045047 1.7688442211055277
[-19.74176867 -13.8280362  -19.97221916 -14.8370704  -17.66222428] -17.20826374287096 1.814070351758794
[-19.67429228 -13.58268695 -20.78908676 -14.92725191 -17.64508309] -17.32368019839837 1.8592964824120604
[-19.64901937 -13.51884642 -20.90158531 -15.10577352 -17.90036984] -17.415118891722805 1.9045226130653266
[-19.31821408 -13.67076178 -20.92692048 -15.26862393 -17.74379132] -17.385662319793234 1.949748743718593
[-19.1452869  -13.67742219 -20.83558995 -15.37357274 -17.59832121] -17.326038597662453 1.9949748743718594
[-19.23861671 -13.59145507 -20.71275027 -15.49695526 -17.64505757] -17.336966976165666 2.040201005025126
[-19.25624385 -13.59325455 -20.65920883 -15.52554567 -17.87899037] -17.382648653849692 2.085427135678392
[-19.22179781 -13.61276489 -21.27442149 -16.20540659 -17.96909679] -17.656697514147996 2.1306532663316586
[-19.08982495 -13.60132874 -21.3450359  -16.4130894  -17.40019353] -17.569894502250555 2.1758793969849246
[-19.15962265 -13.63005514 -20.94289293 -16.42192547 -16.44302021] -17.319503281094065 2.221105527638191
[-19.10297582 -13.76160845 -21.37331559 -16.37282685 -16.91293579] -17.504732498340466 2.2663316582914574
[-19.13059471 -13.94525707 -21.39771392 -16.38290445 -16.91600074] -17.5544941795893 2.3115577889447234
[-19.16310581 -13.95873565 -21.41692324 -16.43526202 -16.85614969] -17.566035281733512 2.35678391959799
[-19.1718413  -13.88036625 -21.51326741 -16.44908699 -16.96560131] -17.596032653116758 2.4020100502512562
[-19.16277161 -13.82330867 -21.56454736 -16.41769706 -17.0271613 ] -17.59909719750166 2.4472361809045227
[-19.16945469 -13.82575323 -20.3289755  -16.43811182 -16.64898754] -17.282256557226717 2.492462311557789
[-19.15768382 -13.84849569 -20.34237412 -16.3116049  -16.97166413] -17.326364532505202 2.5376884422110555
[-19.16196204 -14.20749674 -20.41136507 -16.66590023 -16.97909879] -17.485164572655087 2.582914572864322
[-19.10488546 -14.13541042 -20.46015055 -16.68406839 -16.91666832] -17.46023662680475 2.628140703517588
[-19.14763511 -14.13421361 -20.48261593 -16.69940585 -16.92331046] -17.47743618990552 2.6733668341708543
[-19.15150969 -14.143646   -20.5218878  -16.85516083 -17.0586341 ] -17.54616768641742 2.7185929648241207
[-19.21092757 -14.1119462  -20.37392767 -16.87201136 -17.07145579] -17.528053717549938 2.7638190954773867
[-19.29346656 -14.15988359 -20.54713949 -17.02649049 -17.04650152] -17.61469632990715 2.809045226130653
[-19.29262573 -14.1776595  -20.46015282 -16.98110597 -17.13081344] -17.608471489929777 2.8542713567839195
[-19.31669594 -14.70756007 -20.33965385 -16.72370961 -17.16280046] -17.6500839868047 2.899497487437186
[-19.30020072 -15.79405532 -20.36461026 -16.73818072 -17.24860744] -17.889130893742156 2.9447236180904524
[-19.30635208 -15.45006265 -20.38983767 -16.74224623 -17.53966875] -17.885633475989607 2.9899497487437188
[-19.08773267 -15.40329465 -21.61321352 -16.72465556 -17.6804159 ] -18.10186246009226 3.035175879396985
[-19.09202293 -15.47418076 -21.57522269 -16.79605113 -17.8082964 ] -18.149154780822307 3.080402010050251
[-19.10242303 -15.49351007 -21.5659538  -17.0651807  -17.88394844] -18.22220320950366 3.1256281407035176
[-19.10650746 -15.50315911 -21.63750028 -17.07700879 -18.07341357] -18.279517840149946 3.170854271356784
[-19.11645294 -15.51438983 -21.7026652  -16.93318069 -18.15536326] -18.284410384858443 3.2160804020100504
[-19.11030562 -15.52294076 -21.61600239 -16.94549292 -18.20947071] -18.28084248158377 3.261306532663317
[-19.12390442 -15.51737405 -21.17728222 -16.93719379 -18.31782099] -18.214715094165346 3.306532663316583
[-19.19727316 -15.52423181 -21.15591457 -18.36902368 -18.32948318] -18.515185280996 3.351758793969849
[-19.04332637 -15.53215728 -21.14969039 -18.29359743 -18.33846272] -18.47144683695807 3.3969849246231156
[-19.05778477 -15.53990382 -21.24866706 -18.68002007 -18.35088134] -18.575451414274045 3.442211055276382
[-19.0613793  -15.56510734 -21.27328054 -18.67516529 -18.35939269] -18.586865033363814 3.4874371859296485
[-19.30543537 -15.47151523 -21.28270858 -18.72922419 -19.46159308] -18.850095290052927 3.532663316582915
[-19.29657833 -15.45722088 -21.28486167 -18.6668987  -19.73277485] -18.8876668848972 3.577889447236181
[-19.27133181 -15.46436134 -21.2948115  -18.88728149 -19.74058023] -18.931673277009743 3.6231155778894473
[-19.27450689 -15.24831505 -21.32920411 -18.87641412 -19.95813946] -18.937315926180123 3.6683417085427137
[-19.32560887 -15.14010563 -21.21334165 -18.90196074 -19.97131899] -18.910467174710746 3.71356783919598
[-19.32951192 -15.11337107 -21.22810268 -18.91087583 -19.98419931] -18.9132121646769 3.7587939698492465
[-19.38536315 -15.11975921 -21.23743718 -18.89810511 -20.43256887] -19.01464670258458 3.8040201005025125
[-19.38841963 -15.23060073 -21.39714221 -18.90022526 -20.39071645] -19.061420855938177 3.849246231155779
[-19.37525932 -15.23673325 -21.47581835 -18.98916462 -20.17198033] -19.049791170730238 3.8944723618090453
[-19.38730339 -15.26077793 -21.60641607 -18.97527836 -20.16116287] -19.07818772337484 3.9396984924623117
[-19.43593447 -15.25449438 -21.8112418  -19.15153508 -20.17322691] -19.16528652866065 3.984924623115578
[-19.4493467  -15.25845615 -21.81993741 -19.15552775 -20.18550586] -19.173754771167346 4.030150753768844
[-19.24995468 -15.26261333 -21.79063495 -19.16317701 -20.18783117] -19.13084222644743 4.075376884422111
[-19.25240344 -15.27073737 -21.6628629  -19.12319313 -20.18714286] -19.099267941871084 4.1206030150753765
[-19.25621433 -15.27133797 -21.67091217 -19.12450032 -20.30082385] -19.12475772862611 4.165829145728644
[-19.09802251 -15.27663327 -21.66180072 -19.1315318  -20.19708827] -19.07301531264819 4.211055276381909
[-19.10123629 -16.55333963 -21.53004902 -19.05618386 -20.20863203] -19.289888165237425 4.256281407035176
[-19.10343947 -16.56644612 -21.5375192  -19.07078643 -20.22095877] -19.299829999167464 4.301507537688442
[-19.12528353 -16.59578805 -21.563046   -19.07099544 -20.14146602] -19.299315809385764 4.346733668341709
[-19.12746466 -16.60179496 -21.57550827 -19.07812431 -20.14973668] -19.306525774552377 4.391959798994975
[-19.10545919 -16.53003901 -21.58245526 -19.08403089 -19.75648949] -19.211694767941964 4.437185929648241
[-19.06706888 -16.55053009 -21.58034455 -19.0711893  -19.71898694] -19.197623949745598 4.482412060301508
[-19.06905895 -16.54487965 -21.58700931 -19.31332621 -19.73104412] -19.249063647978804 4.527638190954773
[-19.13102105 -16.55044163 -21.98742467 -19.66086491 -19.70829277] -19.407609005575047 4.572864321608041
[-19.12575422 -16.47524576 -21.99378393 -19.55538987 -20.19276898] -19.468588550690725 4.618090452261306
[-19.12764856 -16.48058322 -21.90659681 -19.68322916 -20.20384407] -19.480380362924432 4.6633165829145735

[-19.15178857 -16.94566396 -21.88504527 -19.68923426 -20.21548573] -19.577443558088486 4.708542713567839
[-19.25059484 -16.94481684 -21.98280056 -19.96030832 -20.22610983] -19.67292607910183 4.7537688442211055
[-19.25238905 -16.94863731 -22.04524051 -19.96598558 -20.20894036] -19.68423856503004 4.798994974874372
[-19.25414986 -17.05918269 -22.12673024 -19.97152241 -20.24551179] -19.731419398024357 4.844221105527638
[-19.25429529 -16.99742048 -22.135899   -19.97816667 -20.30106408] -19.73336910414023 4.889447236180905
[-19.25530246 -17.0030907  -22.14143236 -19.98351586 -20.31014024] -19.738696325445968 4.934673366834171
[-19.38603187 -17.00864945 -22.14685605 -19.98873549 -20.31966937] -19.769988446644323 4.9798994974874375
[-19.38780425 -16.84710692 -22.07796251 -19.90949373 -20.12932289] -19.670338059212803 5.025125628140704
[-19.41892321 -16.85712051 -22.08328023 -19.88640317 -20.12584257] -19.67431393586822 5.07035175879397
[-19.3173279  -16.85728533 -21.92721944 -19.92797021 -20.13464659] -19.632889893449047 5.115577889447236
[-19.31882601 -16.83950841 -21.93246846 -19.93378053 -20.2738955 ] -19.659695780237264 5.160804020100502
[-19.31985862 -16.69817102 -21.93761437 -19.93839144 -20.35149718] -19.649106525992945 5.206030150753769
[-19.32129853 -16.69246735 -22.0692507  -19.9428947  -20.35983315] -19.677148886213153 5.251256281407035
[-19.32458992 -16.69699949 -22.04912621 -19.81872522 -20.35896367] -19.64968090362701 5.296482412060302
[-19.32598057 -16.70144388 -22.05386293 -19.82307442 -20.36701566] -19.654275491776183 5.341708542713568
[-19.32734564 -16.7058025  -22.05850796 -19.94445983 -20.37491168] -19.682205525268134 5.386934673366834
[-19.32868576 -16.70653879 -22.06014481 -19.94856922 -20.38265542] -19.68531879922101 5.432160804020101
[-19.32923821 -16.88897605 -22.06462538 -19.95288754 -20.37638966] -19.72242336689309 5.477386934673367
[-19.33049505 -17.63799406 -22.0690203  -19.95681115 -20.4301689 ] -19.884897890673262 5.522613065326634
[-19.28597641 -17.64285584 -22.08518963 -19.96064716 -20.34074206] -19.863082221331105 5.5678391959799
[-19.29274817 -17.64762402 -22.12502159 -19.96439802 -20.36490541] -19.878939440146766 5.613065326633166
[-19.29545891 -17.70677978 -22.12920388 -19.9680661  -20.43174774] -19.906251282633093 5.658291457286432
[-19.29664749 -17.7113874  -22.13330737 -19.97165371 -20.43860596] -19.910320385587006 5.703517587939698
[-19.29781522 -17.62180189 -22.13733387 -19.97516308 -20.48007645] -19.902438102260955 5.748743718592965
[-20.21313732 -17.62529234 -22.14128514 -20.00957888 -20.57339182] -20.11253710184381 5.793969849246231
[-20.2440014  -17.62968443 -22.15435211 -20.84906131 -20.58885813] -20.29319147728561 5.839195979899498
[-20.24424464 -17.63399371 -22.1581839  -20.85416241 -20.59520464] -20.29715786114856 5.884422110552764
[-20.25300316 -17.63822203 -21.52435788 -20.85800037 -20.60143354] -20.175003396044353 5.9296482412060305
[-20.21798141 -17.77176554 -21.28115846 -20.72965645 -20.60754747] -20.121621866892987 5.974874371859297
[-20.21823362 -17.77553163 -21.2857111  -20.73192865 -20.61354897] -20.12499079276851 6.020100502512563
[-20.212959   -17.77095733 -21.29017899 -20.73414885 -20.61944054] -20.125536942150937 6.06532663316583
[-20.21320042 -17.7749517  -21.29456407 -20.47329758 -20.62548512] -20.076299776973105 6.110552763819095
[-20.21343846 -17.79275039 -21.29886824 -20.46992621 -20.48125687] -20.051248033114454 6.155778894472362
[-20.21367324 -17.79661421 -21.30309334 -20.42528262 -20.46558446] -20.040849575084636 6.201005025125628
[-20.19379674 -17.8399125  -21.30724116 -20.43023357 -20.47113399] -20.048463589548376 6.2462311557788945
[-20.20702082 -17.84362987 -21.31131344 -20.43235095 -20.47658411] -20.054179834596436 6.291457286432161
[-20.20720884 -17.84727972 -23.7395777  -20.43442283 -20.48193695] -20.542085209320767 6.336683417085427
[-20.26230765 -17.85086352 -23.7428048  -20.43645043 -20.48719459] -20.555924198317747 6.381909547738694
[-20.26254899 -17.85438268 -23.74597554 -20.43843493 -20.49235905] -20.55874023764605 6.42713567839196
[-20.26278728 -17.8578386  -23.8949732  -20.44037747 -20.58021869] -20.607239049053742 6.472361809045227
[-20.14978467 -17.86123263 -23.89817433 -20.44227915 -20.58521362] -20.58733687906359 6.517587939698493
[-20.15015088 -17.86456609 -23.94116208 -20.44414104 -20.59012062] -20.59802814044119 6.562814070351759
[-20.15044505 -17.86784027 -23.94424978 -20.30376303 -20.65353855] -20.58396733644139 6.608040201005025
[-20.14124562 -17.84845675 -23.94728502 -20.3055865  -20.65824277] -20.580163334500998 6.653266331658291
[-20.12092262 -17.85161963 -23.95026893 -20.30737286 -20.71269102] -20.588575011809407 6.698492462311558
[-20.1242235  -17.88419565 -23.98476196 -20.30912306 -20.71714864] -20.60389056454131 6.743718592964824
[-20.12445504 -17.8871069  -23.9876316  -20.27122952 -20.75411399] -20.60490740992562 6.788944723618091
[-20.12475281 -17.88996715 -23.99045335 -20.24916419 -20.75843731] -20.602554960427376 6.834170854271357
[-20.12504731 -17.89277748 -23.99465702 -20.25085378 -20.7626862 ] -20.60520435828845 6.8793969849246235
[-20.12533865 -17.89553891 -23.99738595 -20.25250918 -20.76686219] -20.607526973699628 6.92462311557789
[-20.19179204 -17.89825245 -23.98947155 -20.25413124 -20.92827096] -20.652383646486303 6.969849246231156
[-20.2769917  -17.9009191  -23.99213516 -20.25572081 -20.93224657] -20.67160266794708 7.015075376884423
[-20.27741072 -17.98151952 -23.99475539 -20.26221908 -20.92199885] -20.687580712184765 7.060301507537688
[-20.27782437 -17.99143178 -23.99733313 -20.26374881 -20.92598906] -20.69126542796107 7.105527638190955
[-20.30199237 -17.99402955 -23.99986925 -20.16400832 -20.92991228] -20.677962354617563 7.150753768844221
[-20.30238426 -17.99658318 -24.00236462 -20.16544681 -20.93376984] -20.680109742003737 7.1959798994974875
[-20.30277129 -18.98427897 -24.00482007 -20.16685727 -20.93756304] -20.879258126322675 7.241206030150754
[-20.30315357 -18.98611933 -24.0072364  -20.65564678 -20.94129315] -20.97868984749678 7.28643216080402
[-20.36919908 -18.9879274  -24.00961442 -20.65687653 -20.94496141] -20.993715767097477 7.331658291457287
[-20.3696456  -18.98970383 -24.01195489 -20.65808216 -20.94856903] -20.995591100386992 7.376884422110553
[-20.41864864 -18.99144927 -24.01425857 -20.67097042 -20.95211719] -21.00948881592416 7.42211055276382
[-20.41907163 -18.99316436 -24.01652619 -20.67213267 -20.95560704] -21.01130037767064 7.467336683417086
[-20.41948928 -18.99484971 -24.01875848 -20.67327248 -20.95903972] -21.013081934167804 7.5125628140703515
[-20.41990171 -18.99650593 -24.02095613 -20.67439039 -20.96241633] -21.0148340985596 7.557788944723618
[-20.42030903 -19.00243447 -24.02311983 -20.67548692 -20.96573794] -21.017417638850496 7.603015075376884
[-20.42071134 -18.94698651 -24.02525025 -20.67656261 -20.9848141 ] -21.01086496090104 7.648241206030151
[-20.50699512 -18.94853005 -24.02734803 -20.67761793 -20.9880249 ] -21.02970320723899 7.693467336683417
[-20.50739161 -18.95004695 -24.02941382 -20.67865339 -20.94660632] -21.02242241833668 7.738693467336684
[-20.50778334 -18.95153774 -24.03144823 -20.67966946 -20.94970647] -21.02402904696275 7.78391959798995
[-20.50817039 -18.95300296 -24.19467074 -20.68066658 -20.9527568 ] -21.057853494649535 7.8291457286432165
[-20.50637916 -18.95444312 -24.19658494 -20.68164522 -20.9891591 ] -21.0656423085044 7.874371859296483
[-20.50676289 -18.95774669 -24.19568587 -20.6826058  -20.99212329] -21.06698490725231 7.919597989949749
[-20.50714213 -18.95913851 -24.19754254 -20.68354874 -20.9950403 ] -21.068482443357823 7.964824120603016
[-20.50751698 -18.96050675 -24.1866176  -20.68447446 -21.00180061] -21.06818327983064 8.010050251256281
[-20.50788752 -18.96886509 -24.18841772 -20.68538334 -21.00461997] -21.071034728064937 8.055276381909547
[-20.50825383 -18.97020184 -23.9515607  -20.68627579 -21.0116464 ] -21.025587711910216 8.100502512562814
[-20.50985689 -18.97151625 -23.95336636 -20.68715218 -20.63362084] -20.95110250575009 8.145728643216081
[-20.51020883 -18.97280878 -23.95514587 -20.68801287 -20.85458754] -20.996152778095716 8.190954773869347
[-20.47142673 -18.98849228 -23.95689971 -20.18974845 -20.85709192] -20.892731816562325 8.236180904522612
[-20.47176971 -18.98974603 -23.95862835 -20.1906338  -20.8595566 ] -20.894066896730614 8.28140703517588

[-20.47210895 -19.55269571 -23.96033226 -20.19150408 -20.86198232] -21.007724663240943 8.326633165829147
[-20.47244452 -19.55394067 -23.96201188 -20.19235963 -20.86436979] -21.009025299728833 8.371859296482413
[-20.47277649 -19.55516532 -23.96366767 -20.20248189 -20.86671971] -21.01216221477924 8.417085427135678
[-20.49151119 -19.55637005 -23.96530003 -20.20331153 -20.86903274] -21.01710510789645 8.462311557788945
[-20.47548487 -19.55755524 -23.96690941 -20.20412732 -20.87083827] -21.014983021890455 8.507537688442211
[-20.47579683 -19.55872126 -23.96849621 -20.20492956 -20.8730963 ] -21.016208031732354 8.552763819095478
[-20.45101492 -19.55986849 -23.97006083 -20.20571853 -20.87531922] -21.012396399713907 8.597989949748744
[-20.45202774 -19.56099729 -23.97160367 -20.20649452 -20.87404902] -21.013034449348474 8.64321608040201
[-20.45234378 -19.562108   -23.98335367 -20.20725781 -20.87620674] -21.016253998579874 8.688442211055277
[-20.44387114 -19.56320098 -24.00026339 -20.14487002 -20.87833116] -21.006107338225995 8.733668341708544
[-20.4441976  -19.56427656 -24.00177185 -20.14563721 -20.87304517] -21.005785678059887 8.77889447236181
[-20.44452092 -19.56533506 -24.00325963 -20.14639208 -20.87652349] -21.007206235081092 8.824120603015075
[-20.43814276 -19.55218349 -24.00472707 -20.14713488 -20.87854638] -21.004146918432102 8.869346733668342
[-20.43846203 -19.56281371 -24.00617453 -20.14786587 -20.88053831] -21.007170889010677 8.91457286432161
[-20.43877827 -19.56384811 -24.00760235 -20.14858527 -20.88249981] -21.00826276242419 8.959798994974875
[-20.43909153 -19.56486641 -24.00901087 -20.14929333 -20.9282462 ] -21.01810166737625 9.00502512562814
[-20.43940185 -19.56586891 -24.01040042 -20.14999028 -20.9301497 ] -21.019162230863916 9.050251256281408
[-20.48422163 -19.56685591 -24.28302611 -20.15067634 -20.93202436] -21.083360868317154 9.095477386934673
[-20.48453028 -19.56782769 -24.25224922 -20.15135172 -20.93137008] -21.077465796576227 9.14070351758794
[-20.48483606 -19.56878453 -24.25375425 -20.15201664 -20.93319389] -21.078517076081955 9.185929648241206
[-20.48513903 -19.56972672 -24.25265849 -20.15267132 -20.93499027] -21.079037165101987 9.231155778894472
[-20.48543922 -19.57065451 -24.25412626 -20.15331594 -20.93675968] -21.080059124071415 9.27638190954774
[-20.48573668 -19.69112578 -24.25557532 -20.15395071 -20.9385026 ] -21.104978219205865 9.321608040201005
[-20.48603145 -19.69196604 -24.25700598 -20.15399052 -20.94021945] -21.1058426886423 9.366834170854272
[-20.48632357 -19.69279336 -24.27720354 -20.15460685 -20.9419107 ] -21.110567605644725 9.412060301507537
[-20.48661308 -19.69360798 -24.27861426 -20.15521389 -20.94357678] -21.111525199609268 9.457286432160805
[-20.48690003 -19.69441014 -24.28000727 -20.15581182 -20.94521811] -21.112469472718395 9.50251256281407
[-20.48907806 -19.69520006 -24.04326027 -20.15640081 -20.94683511] -21.066154863415285 9.547738693467338
[-20.48936167 -19.69310498 -24.04468296 -20.15698104 -20.94842819] -21.066511767241785 9.592964824120603
[-20.48964281 -19.6938712  -24.04608796 -20.19447178 -20.94999774] -21.074814298351164 9.63819095477387
[-20.48992151 -19.69462583 -24.04747557 -20.1950383  -20.95154418] -21.075721076535178 9.683417085427136
[-20.4901978  -19.69536909 -24.04884606 -20.19559651 -20.95306787] -21.07661546615345 9.728643216080402
[-20.49047173 -19.69610117 -24.0501997  -20.19614658 -20.9545692 ] -21.07749767601852 9.773869346733669
[-20.50522373 -19.69682229 -24.05153674 -20.19668866 -20.95604855] -21.08126399272046 9.819095477386934
[-20.50551761 -19.69753264 -24.05285745 -20.19722289 -20.95750627] -21.08212737263425 9.864321608040202
[-20.50580898 -19.6982324  -24.05416209 -20.19774944 -20.95894272] -21.08297912459029 9.909547738693467
[-20.50609786 -19.69892178 -24.05545089 -20.19826843 -20.96035825] -21.08381944188997 9.954773869346734
[-20.42962236 -19.69960094 -24.15876    -20.19878001 -20.96175322] -21.089703307229723 10.0

In [48]:
a.sort(key=lambda x: x[0])
a

[[-21.112469472718395, 9.50251256281407],
 [-21.111525199609268, 9.457286432160805],
 [-21.110567605644725, 9.412060301507537],
 [-21.1058426886423, 9.366834170854272],
 [-21.104978219205865, 9.321608040201005],
 [-21.089703307229723, 10.0],
 [-21.08381944188997, 9.954773869346734],
 [-21.083360868317154, 9.095477386934673],
 [-21.08297912459029, 9.909547738693467],
 [-21.08212737263425, 9.864321608040202],
 [-21.08126399272046, 9.819095477386934],
 [-21.080059124071415, 9.27638190954774],
 [-21.079037165101987, 9.231155778894472],
 [-21.078517076081955, 9.185929648241206],
 [-21.07749767601852, 9.773869346733669],
 [-21.077465796576227, 9.14070351758794],
 [-21.07661546615345, 9.728643216080402],
 [-21.075721076535178, 9.683417085427136],
 [-21.074814298351164, 9.63819095477387],
 [-21.071034728064937, 8.055276381909547],
 [-21.068482443357823, 7.964824120603016],
 [-21.06818327983064, 8.010050251256281],
 [-21.06698490725231, 7.919597989949749],
 [-21.066511767241785, 9.592964824120603],
 [-21.066154863415285, 9.547738693467338],
 [-21.0656423085044, 7.874371859296483],
 [-21.057853494649535, 7.8291457286432165],
 [-21.02970320723899, 7.693467336683417],
 [-21.025587711910216, 8.100502512562814],
 [-21.02402904696275, 7.78391959798995],
 [-21.02242241833668, 7.738693467336684],
 [-21.019162230863916, 9.050251256281408],
 [-21.01810166737625, 9.00502512562814],
 [-21.017417638850496, 7.603015075376884],
 [-21.01710510789645, 8.462311557788945],
 [-21.016253998579874, 8.688442211055277],
 [-21.016208031732354, 8.552763819095478],
 [-21.014983021890455, 8.507537688442211],
 [-21.0148340985596, 7.557788944723618],
 [-21.013081934167804, 7.5125628140703515],
 [-21.013034449348474, 8.64321608040201],
 [-21.012396399713907, 8.597989949748744],
 [-21.01216221477924, 8.417085427135678],
 [-21.01130037767064, 7.467336683417086],
 [-21.01086496090104, 7.648241206030151],
 [-21.00948881592416, 7.42211055276382],
 [-21.009025299728833, 8.371859296482413],
 [-21.00826276242419, 8.959798994974875],
 [-21.007724663240943, 8.326633165829147],
 [-21.007206235081092, 8.824120603015075],
 [-21.007170889010677, 8.91457286432161],
 [-21.006107338225995, 8.733668341708544],
 [-21.005785678059887, 8.77889447236181],
 [-21.004146918432102, 8.869346733668342],
 [-20.996152778095716, 8.190954773869347],
 [-20.995591100386992, 7.376884422110553],
 [-20.993715767097477, 7.331658291457287],
 [-20.97868984749678, 7.28643216080402],
 [-20.95110250575009, 8.145728643216081],
 [-20.894066896730614, 8.28140703517588],
 [-20.892731816562325, 8.236180904522612],
 [-20.879258126322675, 7.241206030150754],
 [-20.69126542796107, 7.105527638190955],
 [-20.687580712184765, 7.060301507537688],
 [-20.680109742003737, 7.1959798994974875],
 [-20.677962354617563, 7.150753768844221],
 [-20.67160266794708, 7.015075376884423],
 [-20.652383646486303, 6.969849246231156],
 [-20.607526973699628, 6.92462311557789],
 [-20.607239049053742, 6.472361809045227],
 [-20.60520435828845, 6.8793969849246235],
 [-20.60490740992562, 6.788944723618091],
 [-20.60389056454131, 6.743718592964824],
 [-20.602554960427376, 6.834170854271357],
 [-20.59802814044119, 6.562814070351759],
 [-20.588575011809407, 6.698492462311558],
 [-20.58733687906359, 6.517587939698493],
 [-20.58396733644139, 6.608040201005025],
 [-20.580163334500998, 6.653266331658291],
 [-20.55874023764605, 6.42713567839196],
 [-20.555924198317747, 6.381909547738694],
 [-20.542085209320767, 6.336683417085427],
 [-20.29715786114856, 5.884422110552764],
 [-20.29319147728561, 5.839195979899498],
 [-20.175003396044353, 5.9296482412060305],
 [-20.125536942150937, 6.06532663316583],
 [-20.12499079276851, 6.020100502512563],
 [-20.121621866892987, 5.974874371859297],
 [-20.11253710184381, 5.793969849246231],
 [-20.076299776973105, 6.110552763819095],
 [-20.054179834596436, 6.291457286432161],
 [-20.051248033114454, 6.155778894472362],
 [-20.048463589548376, 6.2462311557788945],
 [-20.040849575084636, 6.201005025125628],
 [-19.910320385587006, 5.703517587939698],
 [-19.906251282633093, 5.658291457286432],
 [-19.902438102260955, 5.748743718592965],
 [-19.884897890673262, 5.522613065326634],
 [-19.878939440146766, 5.613065326633166],
 [-19.863082221331105, 5.5678391959799],
 [-19.769988446644323, 4.9798994974874375],
 [-19.738696325445968, 4.934673366834171],
 [-19.73336910414023, 4.889447236180905],
 [-19.731419398024357, 4.844221105527638],
 [-19.72242336689309, 5.477386934673367],
 [-19.68531879922101, 5.432160804020101],
 [-19.68423856503004, 4.798994974874372],
 [-19.682205525268134, 5.386934673366834],
 [-19.677148886213153, 5.251256281407035],
 [-19.67431393586822, 5.07035175879397],
 [-19.67292607910183, 4.7537688442211055],
 [-19.670338059212803, 5.025125628140704],
 [-19.659695780237264, 5.160804020100502],
 [-19.654275491776183, 5.341708542713568],
 [-19.64968090362701, 5.296482412060302],
 [-19.649106525992945, 5.206030150753769],
 [-19.632889893449047, 5.115577889447236],
 [-19.577443558088486, 4.708542713567839],
 [-19.480380362924432, 4.6633165829145735],
 [-19.468588550690725, 4.618090452261306],
 [-19.407609005575047, 4.572864321608041],
 [-19.306525774552377, 4.391959798994975],
 [-19.299829999167464, 4.301507537688442],
 [-19.299315809385764, 4.346733668341709],
 [-19.289888165237425, 4.256281407035176],
 [-19.249063647978804, 4.527638190954773],
 [-19.211694767941964, 4.437185929648241],
 [-19.197623949745598, 4.482412060301508],
 [-19.173754771167346, 4.030150753768844],
 [-19.16528652866065, 3.984924623115578],
 [-19.13084222644743, 4.075376884422111],
 [-19.12475772862611, 4.165829145728644],
 [-19.099267941871084, 4.1206030150753765],
 [-19.07818772337484, 3.9396984924623117],
 [-19.07301531264819, 4.211055276381909],
 [-19.061420855938177, 3.849246231155779],
 [-19.049791170730238, 3.8944723618090453],
 [-19.01464670258458, 3.8040201005025125],
 [-18.937315926180123, 3.6683417085427137],
 [-18.931673277009743, 3.6231155778894473],
 [-18.9132121646769, 3.7587939698492465],
 [-18.910467174710746, 3.71356783919598],
 [-18.8876668848972, 3.577889447236181],
 [-18.850095290052927, 3.532663316582915],
 [-18.586865033363814, 3.4874371859296485],
 [-18.575451414274045, 3.442211055276382],
 [-18.515185280996, 3.351758793969849],
 [-18.47144683695807, 3.3969849246231156],
 [-18.284410384858443, 3.2160804020100504],
 [-18.28084248158377, 3.261306532663317],
 [-18.279517840149946, 3.170854271356784],
 [-18.22220320950366, 3.1256281407035176],
 [-18.214715094165346, 3.306532663316583],
 [-18.149154780822307, 3.080402010050251],
 [-18.10186246009226, 3.035175879396985],
 [-17.889130893742156, 2.9447236180904524],
 [-17.885633475989607, 2.9899497487437188],
 [-17.656697514147996, 2.1306532663316586],
 [-17.6500839868047, 2.899497487437186],
 [-17.61469632990715, 2.809045226130653],
 [-17.608471489929777, 2.8542713567839195],
 [-17.59909719750166, 2.4472361809045227],
 [-17.596032653116758, 2.4020100502512562],
 [-17.569894502250555, 2.1758793969849246],
 [-17.566035281733512, 2.35678391959799],
 [-17.5544941795893, 2.3115577889447234],
 [-17.54616768641742, 2.7185929648241207],
 [-17.528053717549938, 2.7638190954773867],
 [-17.504732498340466, 2.2663316582914574],
 [-17.485164572655087, 2.582914572864322],
 [-17.47743618990552, 2.6733668341708543],
 [-17.46023662680475, 2.628140703517588],
 [-17.415118891722805, 1.9045226130653266],
 [-17.385662319793234, 1.949748743718593],
 [-17.382648653849692, 2.085427135678392],
 [-17.336966976165666, 2.040201005025126],
 [-17.326364532505202, 2.5376884422110555],
 [-17.326038597662453, 1.9949748743718594],
 [-17.32368019839837, 1.8592964824120604],
 [-17.319503281094065, 2.221105527638191],
 [-17.282256557226717, 2.492462311557789],
 [-17.20826374287096, 1.814070351758794],
 [-17.181679169045047, 1.7688442211055277],
 [-17.17164190266228, 1.7236180904522613],
 [-17.145231882153887, 1.4522613065326633],
 [-17.124898819792115, 1.4070351758793969],
 [-17.09913173771377, 1.542713567839196],
 [-17.03345890364771, 1.678391959798995],
 [-17.01936008026763, 1.4974874371859297],
 [-16.980745198189776, 1.6331658291457287],
 [-16.874209056598744, 1.3618090452261307],
 [-16.82422425426731, 1.3165829145728645],
 [-16.801326640288362, 1.5879396984924623],
 [-16.636709345898257, 1.271356783919598],
 [-16.526432329318258, 1.2261306532663316],
 [-16.475057773399403, 1.1809045226130652],
 [-16.445716308439433, 1.135678391959799],
 [-16.40783870832999, 1.0452261306532664],
 [-16.370696947059045, 1.0904522613065326],
 [-16.030646734221644, 1.0]]